version: '3'
services:
  posts-app:
    build:
      dockerfile: Dockerfile
      context: ./posts
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_DBNAME=posts
    depends_on:
      - users-app

  users-app:
    build:
      dockerfile: Dockerfile
      context: ./users
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_DBNAME=users
      - SESSION_SECRET=secret
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
